=== ngsuero/curso-json-xml-JXM-001/jxm-001/data/xml/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">

  <!-- ðŸª Elemento raÃ­z: catÃ¡logo -->
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="producto" type="ProductoType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- ðŸ“¦ Tipo complejo: producto -->
  <xs:complexType name="ProductoType">
    <xs:sequence>
      <xs:element name="nombre">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="50"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="precio">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.01"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="stock">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="categoria">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:length value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="estado">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="nuevo"/>
            <xs:enumeration value="reaco"/>
            <xs:enumeration value="usado"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== ngsuero/curso-json-xml-JXM-001/jxm-001/data/xml/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="catalogo.xsd">
  <producto>
    <nombre>Teclado</nombre>
    <precio>50.00</precio>
    <stock>10</stock>
    <categoria>TEC</categoria>
    <estado>nuevo</estado>
  </producto>

  <producto>
    <nombre>Monitor 24"</nombre>
    <precio>150.50</precio>
    <stock>5</stock>
    <categoria>TEC</categoria>
    <estado>reaco</estado>
  </producto>
</catalogo>
